timeout: 1800s

steps:
- name: calummoore/cloud-builder
  args: ['yarn', 'install']

- name: calummoore/cloud-builder
  args: ['yarn', 'build']

- name: calummoore/cloud-builder
  args: ['yarn', 'deploy']
  env:
  - 'NETLIFY_AUTH_TOKEN=$_NETLIFY_AUTH_TOKEN'
  - 'NETLIFY_SITE_ID=5eae7b71-32d4-4bf7-99ab-dc02d6c3a504'

- name: technosophos/slack-notify
  env:
  - 'SLACK_WEBHOOK=https://hooks.slack.com/services/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'
  - 'SLACK_MESSAGE=Deployed website to PROD'